FROM registry.access.redhat.com/ubi8/ubi
MAINTAINER sig-platform@spinnaker.io
COPY kayenta-web/build/install/kayenta /opt/kayenta
RUN yum -y install java-11-openjdk-headless.x86_64 wget vim ps top
RUN adduser spinnaker
RUN mkdir -p /opt/kayenta/plugins
USER spinnaker
CMD ["/opt/kayenta/bin/kayenta"]
