FROM registry.access.redhat.com/ubi8/ubi:8.3
MAINTAINER sig-platform@spinnaker.io
COPY kayenta-web/build/install/kayenta /opt/kayenta
RUN yum -y install java-11-openjdk-headless.x86_64 wget vim  net-tools curl nettle
RUN yum -y update
RUN adduser spinnaker
RUN mkdir -p /opt/kayenta/plugins
RUN chown -R spinnaker:spinnaker /opt/
USER spinnaker
CMD ["/opt/kayenta/bin/kayenta"]
